// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DependentSelectController from "./dependent_select_controller"
import AutosubmitController from "./autosubmit_controller"
import AutoHidePaginationController from "./auto_hide_pagination_controller"
import PerPageController from "./per_page_controller"
import WikilinkPreviewController from "./wikilink_preview_controller"
import TagAutocompleteController from "./tag_autocomplete_controller"

application.register("dependent-select", DependentSelectController)
application.register("autosubmit", AutosubmitController)
application.register("auto-hide-pagination", AutoHidePaginationController)
application.register("per-page", PerPageController)
application.register("wikilink-preview", WikilinkPreviewController)
application.register("tag-autocomplete", TagAutocompleteController)

