// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DependentSelectController from "./dependent_select_controller"
import AutosubmitController from "./autosubmit_controller"
import AutoHidePaginationController from "./auto_hide_pagination_controller"
import PerPageController from "./per_page_controller"
import WikilinkPreviewController from "./wikilink_preview_controller"
import TagAutocompleteController from "./tag_autocomplete_controller"
import LiveSearchController from "./live_search_controller"
import ModalController from "./modal_controller"
import AutocompleteController from "./autocomplete_controller"
import DropdownController from "./dropdown_controller"
import GoTopController from "./go_top_controller";
import DynamicElementsController from "./dynamic_elements_controller";
import MorphemeConstructorController from "./morpheme_constructor_controller";
import ToggleVisibilityController from "./toggle_visibility_controller"

application.register("dependent-select", DependentSelectController)
application.register("autosubmit", AutosubmitController)
application.register("auto-hide-pagination", AutoHidePaginationController)
application.register("per-page", PerPageController)
application.register("wikilink-preview", WikilinkPreviewController)
application.register("tag-autocomplete", TagAutocompleteController)
application.register("live-search", LiveSearchController)
application.register("modal", ModalController)
application.register("autocomplete", AutocompleteController)
application.register("dropdown", DropdownController)
application.register('go-top', GoTopController)
application.register("dynamic-elements", DynamicElementsController)
application.register("morpheme-constructor", MorphemeConstructorController)
application.register("toggle-visibility", ToggleVisibilityController)
