version: "3.8"

services:
  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"

  web:
    image: anive-world:latest

    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      # В production этот volume лучше убрать, чтобы код был только внутри образа
      - .:/rails
    env_file:
      - .env

volumes:
  postgres_data:
